import Image from 'next/image';

export default function Terms() {
  return (
    <div className="min-h-screen bg-cream-50 pt-20 px-4 pb-16">
      <div className="max-w-3xl mx-auto">
        <div className="flex justify-center mb-8">
          <Image src="/rts-logo.png" alt="RTS Logo" width={180} height={50} />
        </div>
        <h1 className="text-3xl font-bold text-center mb-8">Terms & Conditions</h1>
        <div className="prose prose-lg max-w-none text-gray-800">
          <h2>PRIVACY POLICY</h2>
          <p>This privacy policy applies to all Users who access the Platform, and they are therefore required to read and understand the Policy before submitting any Personal Information (as defined hereinafter). This privacy policy governs your use of the &apos;PhysicsWallah&apos; application, PhysicsWallah YouTube Channel, www.physicswallah.live (&quot;Website&quot;), and other associated applications, products, websites, and services managed by the Company. By submitting Personal Information, you consent to the use and processing of such information in accordance with this Policy. Third-party websites may place their own cookies or other files on Users&apos; computers, collect data, or solicit personal information from Users, for which PhysicsWallah is not responsible or liable. Accordingly, PhysicsWallah does not make any representations concerning the privacy practices or policies of such third parties or the terms of use of such websites, nor does PhysicsWallah guarantee the accuracy, integrity, or quality of the information, data, text, software, sound, photographs, graphics, videos, messages, or other materials available on such websites/applications. The inclusion or exclusion of any such link does not imply any endorsement by PhysicsWallah of the website, its provider, or the information on the website/application. PhysicsWallah encourages Users to read the privacy policies of each such website/application, and Users understand that it is solely the responsibility of the third party to ensure compliance in this regard. PhysicsWallah has taken reasonable precautions as per applicable Indian law and has implemented industry standards to treat Personal Information as confidential and to protect it from unauthorized access, improper use or disclosure, modification, unlawful destruction, or accidental loss of the Personal Information. We will not use or share your information with anyone except as described in this Privacy Policy. Each time you use our Service, you are accepting the practices described in this Privacy Policy at that time.</p>
          <h2>USAGE AND RETENTION OF INFORMATION</h2>
          <p>We obtain the information you provide when you access and register on the Application, Website, YouTube Channel, Services, or products. When you register with us, you generally provide: (a) your name, age, email address, location, phone number, password, and educational interests; (b) transaction-related information, such as when you make purchases, respond to offers, or download and use applications from us; (c) information you provide when you contact us for help; and (d) information you enter into our system while using the Application, Website, YouTube Channel, Services, or products, such as when asking questions, participating in discussions, or taking tests. The information collected from users can be categorized as &quot;Personal Information,&quot; &quot;Sensitive Personal Information,&quot; and &quot;Associated Information.&quot; Personal Information, Sensitive Personal Information, and Associated Information (each as defined under the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 (the &quot;Data Protection Rules&quot;)) shall collectively be referred to as &apos;Information&apos; in this Policy. We may use the Information to contact you from time to time to provide you with Services, important updates, required notices, and marketing promotions. We will use your Personal Information to provide, analyze, administer, and improve our services, offer you a personalized experience on our Website/Application (especially by suggesting services tailored to your needs), contact you regarding your account and our services, provide customer support, offer personalized marketing, and detect, prevent, mitigate, and investigate fraudulent or illegal activities. Additionally, we use your Personal Information to determine your general geographic location, provide localized courses and classes, offer customized study materials and recommendations, identify your Internet service provider, and efficiently respond to inquiries and requests. We also use your information to enforce our terms and communicate with you about our services (via email, push notifications, text messages, and online messaging channels). This allows us to send you details about new features, content available on the Website/Application, special offers, promotional announcements, surveys, and help with operational requests such as password resets.</p>
          <h2>COOKIES</h2>
          <p>We send cookies (small files containing a string of characters) to your computer, which uniquely identify your browser. Cookies are used to track your preferences, help you log in faster, and are aggregated to identify user trends. This data is used to improve our offerings, such as providing more content in areas of greater interest to the majority of users. Most browsers are initially set to accept cookies, but you can reset your browser to refuse all cookies or to alert you when a cookie is being sent. However, some of our features and services may not function properly if cookies are disabled.</p>
          <h2>SHARING AND DISCLOSING PERSONAL INFORMATION</h2>
          <p>We use other companies, agents, or contractors (&quot;Service Providers&quot;) to perform services on our behalf or to assist us in providing services to you. We engage Service Providers to offer marketing, advertising, communications, infrastructure, and IT services, to personalize and optimize our service, to process credit card transactions or other payment methods, to provide customer support, to collect debts, to analyze and enhance data, and to process and administer consumer surveys. In the course of providing these services, these Service Providers may have access to your personal or other information. We do not authorize them to use or disclose your personal information except in connection with providing their services. We shall use your Personal Information to ensure that services related to the Platform are presented to you most effectively, to secure the Platform and improve its functionality, to fulfill our obligations to you, and to communicate with you. This communication may include calls, texts, or emails, and can be for transactional, service-related, or promotional purposes. If at any time you wish to stop receiving communication from us, you can opt-out by writing to us.</p>
          <h2>INFORMATION SECURITY</h2>
          <p>We do not sell, transfer, or rent your personal information to third parties for their marketing purposes without your explicit consent, and we only use your information as described in &apos;Privacy Policy&apos;. We consider the protection of your privacy to be a key principle of our community. We clearly understand that you and your information are among our most valuable assets. Your personal information is stored and processed on computers located in India, which are protected by both physical and technological security measures. We use third parties to verify and certify our privacy practices. If you object to your information being transferred or used in this way, please do not use this Website/Application. Under no circumstances do we rent, trade, transfer, or share your personal information with any other company for their marketing purposes without your consent. However, we reserve the right to disclose your personal information to any third party that makes a legally-compliant request for its disclosure.</p>
          <h2>PUBLIC FORUMS</h2>
          <p>When you use certain features on our Website/Application/YouTube Channel, such as discussion forums, and post or share personal information like comments, messages, files, or photos, this information will be available to all users and will be in the public domain. Any sharing of information is done at your own risk. Please keep in mind that if you disclose personal information in your profile or when posting on our forums, this information may become publicly accessible.</p>
          <h2>CONSULTING</h2>
          <p>We use third parties to help us provide services to You including the fulfillment of service, processing of payments, monitoring site activity, conducting surveys, maintaining our database, administering emails, and administering contents, and to provide aggregate, comparative information on the performance of our Website/Application to us and a select group.</p>
          <h2>USER CUSTOMS</h2>
          <p>You have the option to customize how we use your personal information, including how we communicate with you, send marketing information, provide customized and relevant advertising, and whether you want to remain signed into your account. If you do not wish to receive marketing communications from us, you can unsubscribe using the link in the email you receive or update your communication preferences. You can also contact us via email to block promotional communications. Please note, we do not sell or rent your personal information to third parties for their marketing purposes without your explicit consent.</p>
          <h2>OWNERSHIP OF RIGHTS</h2>
          <p>All rights, including copyright, in this Website/Application are owned by or licensed to us. Any use of this Website/Application or its contents, including copying or storing them in whole or in part, other than for your own personal, non-commercial use, is prohibited without our permission. You are prohibited from modifying, copying, distributing, transmitting, displaying, printing, publishing, selling, licensing, creating derivative works from, or using any content available on or through our Website/Application for commercial or public purposes. You may not modify, distribute, or repost anything from this Website/Application for any purpose. You acknowledge that downloading copyrighted material does not grant you any ownership rights. Trademarks located on or within our Website/Application, or on any Website/Application owned or operated in conjunction with PhysicsWallah, shall not be considered public domain. These trademarks are the exclusive property of PhysicsWallah, unless the site is under license from the trademark owner, in which case the license is for the exclusive benefit and use of PhysicsWallah, unless otherwise stated.</p>
          <h2>CONSENT</h2>
          <p>We believe that every user of our YouTube Channel, Services, products, Website, or Application must be able to provide informed consent before providing any information required for using these services. In the case of minors, consent for the retention of data is considered to be given by their guardians or parents. By registering with us, you expressly consent to our collection, processing, storing, disclosing, and handling of your information as described in this Policy, including any amendments we may make. It is understood that, at the time of registration, the parents or guardians of a minor agree to the privacy policy and terms and conditions of the company. Processing your information, including but not limited to collecting, storing, deleting, using, combining, sharing, transferring, and disclosing, will take place in India. If you reside outside India, your information will be transferred, processed, and stored in accordance with the applicable data protection laws of India. By submitting content on or through the Services (your &quot;Material&quot;), you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display, and distribute such Material in any and all media or distribution methods (now known or later developed) and to associate your Material with you, except as described below. You agree that others may use your Material in the same way as any other content available through the Services. Other users of the Services may fork, tweak, and repurpose your Material in accordance with these Terms. If you delete your user account, your Material and name may remain accessible through the Services.</p>
          <h2>EXCLUSIVE SERVICE</h2>
          <p>By having a PhysicsWallah account, you explicitly consent to us capturing images and accessing camera/microphone permissions for making and recording video calls.</p>
          <h2>SECURITY</h2>
          <p>We are committed to safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect the information we process and maintain. For example, we limit access to this information to authorized employees who need it to operate, develop, or improve our YouTube Channel, Services, products, Website, or Application. Please be aware that, although we strive to provide reasonable security for the information we process and maintain, no security system can prevent all potential security breaches. PhysicsWallah may disclose information in the following situations: as required by law; to enforce applicable &quot;Terms of Use,&quot; including investigating potential violations thereof; when we believe in good faith that disclosure is necessary to protect our rights, your safety, or the safety of others, investigate fraud, address security or technical issues, or respond to a government request; and with our trusted service providers.</p>
          <h2>CONSENT TO THIS POLICY</h2>
          <p>The Terms of Use Agreement is incorporated herein by reference in its entirety. By submitting data to us or our agent or using the Site, you consent to our use of your data in the manner set out in this Privacy Policy.</p>
          <h2>UPDATES TO POLICY</h2>
          <p>As the Company evolves, our privacy policy will need to evolve as well to cover new situations. You are advised to review this Policy regularly for any changes, as continued use is deemed approval of all changes.</p>
          <h2>LIMITATION OF LIABILITY</h2>
          <p>The user acknowledges that the company is not the manufacturer of the content on the Website, Application, or YouTube Channel and shall not be liable for any repercussions related to the content. In no event shall the Company, its officers, directors, employees, partners, or agents be liable to you or any third party for any special, incidental, indirect, consequential, or punitive damages whatsoever, including those resulting from loss of use, data, or profits, or any other claim arising out of or in connection with your use of or access to the Website, Application, or YouTube Channel. In the event of your breach of these Terms, you agree that the Company will be irreparably harmed and may not have an adequate remedy in money or damages. The Company&apos;s right to obtain such relief shall not limit its right to seek other remedies. Any violation by you of the terms of this Clause may result in the immediate suspension or termination of your accounts, in addition to any legal remedies available to the Company. In such instances, the Company may also disclose your account information if required by any governmental or legal authority. You understand that a violation of these Terms could also result in civil or criminal liability under applicable laws.</p>
          <h2>REFUND POLICY</h2>
          <p>When you purchase our products or services, your purchase is not entitled for any refund. If you buy any Online Test/Offline Test/Service, it is non-refundable. We recommend checking the complete details before making a payment. If the product received is damaged or lost by the courier partner, you are entitled to a replacement. However, if the address provided is incorrect or the books are not accepted by the student, no refund will be issued. Registration fees, which are part of the test series fees, are non-refundable. Students will receive access to offline tests, proctored tests, test analysis, performance analysis, and other resources from the test start date until the end date as per the schedule.</p>
          <h2>ACCOUNT DELETION</h2>
          <p>Send an email to our customer care service at support@pw.live and our team with a request of account deletion. Our team will reach out to you and will delete your account upon your confirmation within 96 hours.</p>
          <h2>IOS POLICY</h2>
          <p>Dear students, If you&apos;re using iOS version 14 or later, you&apos;ll have access to new features that enhance your experience. These features are designed to improve usability, make navigation easier, and provide a smoother learning environment. Please make sure your device is updated to iOS 14 or higher to take full advantage of these improvements.</p>
          <h2>Disclaimer</h2>
          <p>The Proctored Test feature is available on both Android and iOS devices. However, certain functionalities or user experiences may vary or have limitations on iOS devices. The customer acknowledges and agrees that while the Proctored Test feature is available on iOS devices, certain functionalities may have limitations or not function as expected. By using the Proctored Test feature on either platform, the customer agrees to indemnify, defend, and hold harmless PhysicsWallah Pvt. Ltd., its affiliates, officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, and expenses, including legal fees and costs, arising out of or in any way connected with (i) the use or performance of the Proctored Test feature, including any limitations on iOS devices, and (ii) any breach of this agreement by the customer.</p>
          <h2>CONTACT US</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us: By visiting this page on our Website/Application: https://www.physicswallah.live/ By emailing us at: support@physicswallah.org</p>
        </div>
        <div className="mt-12 flex justify-center">
          <a href="https://www.instagram.com/testseries_pw/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-purple-800 text-white rounded-lg font-bold shadow hover:scale-105 transition-transform">
            <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M7.75 2h8.5A5.75 5.75 0 0 1 22 7.75v8.5A5.75 5.75 0 0 1 16.25 22h-8.5A5.75 5.75 0 0 1 2 16.25v-8.5A5.75 5.75 0 0 1 7.75 2zm0 1.5A4.25 4.25 0 0 0 3.5 7.75v8.5A4.25 4.25 0 0 0 7.75 20.5h8.5A4.25 4.25 0 0 0 20.5 16.25v-8.5A4.25 4.25 0 0 0 16.25 3.5h-8.5zm4.25 3.25a5.25 5.25 0 1 1 0 10.5a5.25 5.25 0 0 1 0-10.5zm0 1.5a3.75 3.75 0 1 0 0 7.5a3.75 3.75 0 0 0 0-7.5zm6 1.25a1 1 0 1 1-2 0a1 1 0 0 1 2 0z"></path></svg>
            Follow us on Instagram
          </a>
        </div>
      </div>
    </div>
  );
} 